//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GratisForGratis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CATEGORIA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CATEGORIA()
        {
            this.ALIMENTAZIONE = new HashSet<ALIMENTAZIONE>();
            this.ARTISTA = new HashSet<ARTISTA>();
            this.AUTORE = new HashSet<AUTORE>();
            this.BROWSER = new HashSet<BROWSER>();
            this.FORMATO = new HashSet<FORMATO>();
            this.GENERE = new HashSet<GENERE>();
            this.PERSONA_RICERCA = new HashSet<PERSONA_RICERCA>();
            this.PIATTAFORMA = new HashSet<PIATTAFORMA>();
            this.REGISTA = new HashSet<REGISTA>();
            this.SISTEMA_OPERATIVO = new HashSet<SISTEMA_OPERATIVO>();
            this.MARCA = new HashSet<MARCA>();
            this.ANNUNCIO = new HashSet<ANNUNCIO>();
        }
    
        public int ID { get; set; }
        public Nullable<int> ID_PADRE { get; set; }
        public string NOME { get; set; }
        public string DESCRIZIONE { get; set; }
        public string IMMAGINE { get; set; }
        public short LIVELLO { get; set; }
        public int TIPO_VENDITA { get; set; }
        public int STATO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ALIMENTAZIONE> ALIMENTAZIONE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ARTISTA> ARTISTA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AUTORE> AUTORE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BROWSER> BROWSER { get; set; }
        public virtual CATEGORIA CATEGORIA1 { get; set; }
        public virtual CATEGORIA CATEGORIA2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FORMATO> FORMATO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GENERE> GENERE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PERSONA_RICERCA> PERSONA_RICERCA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PIATTAFORMA> PIATTAFORMA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REGISTA> REGISTA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SISTEMA_OPERATIVO> SISTEMA_OPERATIVO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MARCA> MARCA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ANNUNCIO> ANNUNCIO { get; set; }
    }
}
