//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GratisForGratis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTO_CORRENTE_MONETA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CONTO_CORRENTE_MONETA()
        {
            this.OFFERTA_CONTO_CORRENTE_MONETA = new HashSet<OFFERTA_CONTO_CORRENTE_MONETA>();
        }
    
        public int ID { get; set; }
        public System.Guid ID_CONTO_CORRENTE { get; set; }
        public int ID_MONETA { get; set; }
        public Nullable<int> ID_TRANSAZIONE { get; set; }
        public System.DateTime DATA_INSERIMENTO { get; set; }
        public Nullable<System.DateTime> DATA_MODIFICA { get; set; }
        public int STATO { get; set; }
    
        public virtual CONTO_CORRENTE CONTO_CORRENTE { get; set; }
        public virtual MONETA MONETA { get; set; }
        public virtual TRANSAZIONE TRANSAZIONE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OFFERTA_CONTO_CORRENTE_MONETA> OFFERTA_CONTO_CORRENTE_MONETA { get; set; }
    }
}
