//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GratisForGratis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CORRIERE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CORRIERE()
        {
            this.CORRIERE_NAZIONE = new HashSet<CORRIERE_NAZIONE>();
        }
    
        public int ID { get; set; }
        public string NOME { get; set; }
        public string DESCRIZIONE { get; set; }
        public string CHIAVE { get; set; }
        public string PASSWORD { get; set; }
        public string NUMERO_LICENZA { get; set; }
        public string TOKEN { get; set; }
        public System.DateTime DATA_INSERIMENTO { get; set; }
        public System.DateTime DATA_MODIFICA { get; set; }
        public int STATO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CORRIERE_NAZIONE> CORRIERE_NAZIONE { get; set; }
    }
}
