//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GratisForGratis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MODELLO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MODELLO()
        {
            this.OGGETTO_TELEFONO = new HashSet<OGGETTO_TELEFONO>();
            this.OGGETTO_COMPUTER = new HashSet<OGGETTO_COMPUTER>();
            this.OGGETTO_ELETTRODOMESTICO = new HashSet<OGGETTO_ELETTRODOMESTICO>();
            this.OGGETTO_GIOCO = new HashSet<OGGETTO_GIOCO>();
            this.OGGETTO_SPORT = new HashSet<OGGETTO_SPORT>();
            this.OGGETTO_STRUMENTO = new HashSet<OGGETTO_STRUMENTO>();
            this.OGGETTO_TECNOLOGIA = new HashSet<OGGETTO_TECNOLOGIA>();
            this.OGGETTO_VEICOLO = new HashSet<OGGETTO_VEICOLO>();
        }
    
        public int ID { get; set; }
        public string NOME { get; set; }
        public string DESCRIZIONE { get; set; }
        public int ID_MARCA { get; set; }
        public System.DateTime DATA_INSERIMENTO { get; set; }
        public Nullable<System.DateTime> DATA_MODIFICA { get; set; }
        public int STATO { get; set; }
    
        public virtual MARCA MARCA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OGGETTO_TELEFONO> OGGETTO_TELEFONO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OGGETTO_COMPUTER> OGGETTO_COMPUTER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OGGETTO_ELETTRODOMESTICO> OGGETTO_ELETTRODOMESTICO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OGGETTO_GIOCO> OGGETTO_GIOCO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OGGETTO_SPORT> OGGETTO_SPORT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OGGETTO_STRUMENTO> OGGETTO_STRUMENTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OGGETTO_TECNOLOGIA> OGGETTO_TECNOLOGIA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OGGETTO_VEICOLO> OGGETTO_VEICOLO { get; set; }
    }
}
