//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GratisForGratis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSONA_SEGNALAZIONE
    {
        public int ID { get; set; }
        public int ID_PERSONA { get; set; }
        public string EMAIL_RISPOSTA { get; set; }
        public string OGGETTO { get; set; }
        public string TESTO { get; set; }
        public string ALLEGATO { get; set; }
        public string CONTROLLER { get; set; }
        public string VISTA { get; set; }
        public string IP { get; set; }
        public string MAC_ADDRESS { get; set; }
        public System.DateTime DATA_INVIO { get; set; }
        public int STATO { get; set; }
    
        public virtual PERSONA PERSONA { get; set; }
    }
}
