//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GratisForGratis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SPEDIZIONE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SPEDIZIONE()
        {
            this.ANNUNCIO_SPEDIZIONE = new HashSet<ANNUNCIO_SPEDIZIONE>();
        }
    
        public int ID { get; set; }
        public int ID_CORRIERE_NAZIONE { get; set; }
        public string NOME_MITTENTE { get; set; }
        public string TELEFONO_MITTENTE { get; set; }
        public string EMAIL_MITTENTE { get; set; }
        public int ID_INDIRIZZO_MITTENTE { get; set; }
        public string NOME_DESTINATARIO { get; set; }
        public string TELEFONO_DESTINATARIO { get; set; }
        public string EMAIL_DESTINATARIO { get; set; }
        public Nullable<int> ID_INDIRIZZO_DESTINATARIO { get; set; }
        public System.DateTime DATA_INSERIMENTO { get; set; }
        public Nullable<System.DateTime> DATA_MODIFICA { get; set; }
        public int STATO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ANNUNCIO_SPEDIZIONE> ANNUNCIO_SPEDIZIONE { get; set; }
        public virtual CORRIERE_NAZIONE CORRIERE_NAZIONE { get; set; }
        public virtual INDIRIZZO INDIRIZZO { get; set; }
        public virtual INDIRIZZO INDIRIZZO1 { get; set; }
    }
}
