//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GratisForGratis.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Email {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Email() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GratisForGratis.App_GlobalResources.Email", typeof(Email).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offerta di.
        /// </summary>
        public static string BidOf {
            get {
                return ResourceManager.GetString("BidOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offerta per la vendita.
        /// </summary>
        public static string BidSubject {
            get {
                return ResourceManager.GetString("BidSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ricevi questa e-mail perch&amp;egrave; risulti iscritto al servizio di {0} Se hai ricevuto questo messaggio per errore o non hai mai aderito al servizio di {1} , accedi e disiscriviti o contattaci nella sezione contatti del sito.&lt;br /&gt;&lt;br /&gt;Tutti i diritti riservati | Copyright &amp;reg;.
        /// </summary>
        public static string Footer {
            get {
                return ResourceManager.GetString("Footer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Richiesta nuova password.
        /// </summary>
        public static string ForgotPasswordSubject {
            get {
                return ResourceManager.GetString("ForgotPasswordSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abbiamo &lt;strong&gt;resettato la tua password&lt;/strong&gt; e te ne abbiamo &lt;strong&gt;generata una nuova&lt;/strong&gt;. Accedi con le credenziali qui di seguito e personalizza la tua password..
        /// </summary>
        public static string ForgotPasswordText1 {
            get {
                return ResourceManager.GetString("ForgotPasswordText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Torna con noi a far &lt;strong&gt;parte di un commercio alternativo!&lt;/strong&gt; &lt;br /&gt;&lt;strong&gt;Aumenta il tuo credito&lt;/strong&gt; senza alcuno sforzo!.
        /// </summary>
        public static string ForgotPasswordText2 {
            get {
                return ResourceManager.GetString("ForgotPasswordText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ciao &lt;b&gt;{0}&lt;/b&gt;.
        /// </summary>
        public static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuova password.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rivalorizza sempre ciò che sei e ti circonda!.
        /// </summary>
        public static string PaymentFooter {
            get {
                return ResourceManager.GetString("PaymentFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pagamento {0} di {1} dal portale {2}.
        /// </summary>
        public static string PaymentFromPartnersSubject {
            get {
                return ResourceManager.GetString("PaymentFromPartnersSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storico pagamenti.
        /// </summary>
        public static string PaymentHistorical {
            get {
                return ResourceManager.GetString("PaymentHistorical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pagamento {0} di {1}.
        /// </summary>
        public static string PaymentSubject {
            get {
                return ResourceManager.GetString("PaymentSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hai ricevuto il pagamento per &lt;b&gt;{0}&lt;/b dall&apos;&lt;b&gt;utente&lt;/b&gt; {1}.&lt;br /&gt;Qui di seguito troverai il link per verificare la ricezione del pagamento:.
        /// </summary>
        public static string PaymentText1 {
            get {
                return ResourceManager.GetString("PaymentText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;Pagamento effettuato dal portale {0}.&lt;/b&gt;.
        /// </summary>
        public static string PaymentText2 {
            get {
                return ResourceManager.GetString("PaymentText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrazione avvenuta con successo!.
        /// </summary>
        public static string RegistrationSubject {
            get {
                return ResourceManager.GetString("RegistrationSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collegandosi al sito {0} potrai fin da subito usufruire del tuo bonus!&lt;br /&gt;In più pubblicando 4 annunci di vendita, otterrai subito ulteriori {1} punti bonus, il corrispettivo quindi di € {2}!.
        /// </summary>
        public static string RegistrationText1 {
            get {
                return ResourceManager.GetString("RegistrationText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conferma ed entra nel nuovo mondo del commercio online!&lt;br /&gt;.
        /// </summary>
        public static string RegistrationText2 {
            get {
                return ResourceManager.GetString("RegistrationText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confermiamo la corretta registrazione al servizio.&lt;br /&gt;Qui di seguito troverai il link per confermare la tua adesione:.
        /// </summary>
        public static string RegistrationTextForLink {
            get {
                return ResourceManager.GetString("RegistrationTextForLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se hai ricevuto questa mail per sbaglio o non vuoi più essere avvertito per questa ricerca, clicca il seguente link: {0}.
        /// </summary>
        public static string SearchNotifyFooter {
            get {
                return ResourceManager.GetString("SearchNotifyFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifica sulla ricerca per {0}.
        /// </summary>
        public static string SearchNotifySubject {
            get {
                return ResourceManager.GetString("SearchNotifySubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Come da te richiesto, ti avvisiamo che è stato appena pubblicata la vendita di {0}. Se desideri ancora effettuare l&apos;acquisto, clicca nel link sottostante:.
        /// </summary>
        public static string SearchNotifyText1 {
            get {
                return ResourceManager.GetString("SearchNotifyText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se hai ricevuto questa mail per sbaglio o non vuoi più essere avvertito per questa ricerca, clicca il seguente link: {0}.
        /// </summary>
        public static string SearchSaveFooter {
            get {
                return ResourceManager.GetString("SearchSaveFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salvataggio ricerca per {0}.
        /// </summary>
        public static string SearchSaveSubject {
            get {
                return ResourceManager.GetString("SearchSaveSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grazie al &lt;strong&gt;salvataggio della ricerca per {0}&lt;/strong&gt;, potrai ricevere &lt;strong&gt;in tempo reale la notifica&lt;/strong&gt; di quando verrà pubblicato ciò che desideri e stai cercando!.
        /// </summary>
        public static string SearchSaveText1 {
            get {
                return ResourceManager.GetString("SearchSaveText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ti auguriamo una &lt;strong&gt;buona giornata da {0}&lt;/strong&gt;.
        /// </summary>
        public static string SearchSaveText2 {
            get {
                return ResourceManager.GetString("SearchSaveText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commercia in maniera innovativa!.
        /// </summary>
        public static string SloganFooter {
            get {
                return ResourceManager.GetString("SloganFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benvenuto su {0}!.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
    }
}
