//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GratisForGratis.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MetaTag {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MetaTag() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GratisForGratis.App_GlobalResources.MetaTag", typeof(MetaTag).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hai dei dubbi o vuoi partecipare con noi a quest&apos;avventura? Inviaci una richiesta di colloquio. Amiamo la partecipazione sociale..
        /// </summary>
        public static string DescriptionContatti {
            get {
                return ResourceManager.GetString("DescriptionContatti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} elimina disuguaglianze, rivaluta l&apos;usato e rivaluta le qualità personali dell&apos;individuo. Proponiamo un motore sociale per la crescita..
        /// </summary>
        public static string DescriptionCosaFacciamo {
            get {
                return ResourceManager.GetString("DescriptionCosaFacciamo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oggetti rotti, inutilizzati, utili per hobby o per la creazione di nuove idee, fantastici da regalare. Se vuoi puoi anche proporti per il volontariato e regalare un pò del tuo tempo..
        /// </summary>
        public static string DescriptionGift {
            get {
                return ResourceManager.GetString("DescriptionGift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compra gratuitamente {0} della categoria {1}. In vendita a {2} con {3} crediti o prova con il baratto..
        /// </summary>
        public static string DescriptionGood {
            get {
                return ResourceManager.GetString("DescriptionGood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acquista gratuitamente oggetti o servizi di qualsiasi tipo! Le migliori vendite gratuite del nostro portale..
        /// </summary>
        public static string DescriptionGratis {
            get {
                return ResourceManager.GetString("DescriptionGratis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acquista gratuitamente gli oggetti che desideri. Compra servizi personali, aziendali o domestici e aumenta il tuo tempo libero..
        /// </summary>
        public static string DescriptionHome {
            get {
                return ResourceManager.GetString("DescriptionHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ecco l&apos;elenco delle grandi realtà che hanno deciso di incamminarsi insieme a noi! Progetti che migliorano la persona e il gruppo sociale..
        /// </summary>
        public static string DescriptionPartners {
            get {
                return ResourceManager.GetString("DescriptionPartners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Il rispetto della privacy per noi è fondamentale. Ci teniamo a tutelare ogni vostro interesse prima del nostro..
        /// </summary>
        public static string DescriptionPrivacy {
            get {
                return ResourceManager.GetString("DescriptionPrivacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grandi offerte su {1} della categoria {0}. Scopri le migliori novità gratuite o acquistabili con baratto. Regala, compra o scambia liberamente!.
        /// </summary>
        public static string DescriptionSearch {
            get {
                return ResourceManager.GetString("DescriptionSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compra gratuitamente {0} della categoria {1}. In vendita a {2} con {3} crediti o prova con il baratto..
        /// </summary>
        public static string DescriptionService {
            get {
                return ResourceManager.GetString("DescriptionService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Siti web di utilità sociale ed umana.
        /// </summary>
        public static string DescriptionSiteWeb {
            get {
                return ResourceManager.GetString("DescriptionSiteWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contatti, dubbi, partecipare, partecipazione sociale, inviaci un tuo contatto.
        /// </summary>
        public static string KeywordsContatti {
            get {
                return ResourceManager.GetString("KeywordsContatti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elimina le disuguaglianze, rivaluta oggetto, rivaluta servizi, crescita umana, spazio culturale, rinnovo dei beni.
        /// </summary>
        public static string KeywordsCosaFacciamo {
            get {
                return ResourceManager.GetString("KeywordsCosaFacciamo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to oggetti rotti, oggetti inutilizzati, hobby, nuove idee, regalare, volontariato, tempo.
        /// </summary>
        public static string KeywordsGift {
            get {
                return ResourceManager.GetString("KeywordsGift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compra gratuitamente, categoria, vendita, baratto, acquista, {0}, {1}, {2}, {3} crediti.
        /// </summary>
        public static string KeywordsGood {
            get {
                return ResourceManager.GetString("KeywordsGood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tutto gratis, oggetti gratis, servizi gratis, acquista gratuitamente, vendite gratuite.
        /// </summary>
        public static string KeywordsGratis {
            get {
                return ResourceManager.GetString("KeywordsGratis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compra gratis, acquista gratuitamente, oggetti, compra servizi, compra arredamento,compra abbigliamento, compra musica, compra giochi, compra sport e tempo libero, compra elettronica, compra videoteca, compra cartoleria e libreria, compra veicoli, compra fai da te, compra servizi domestici, compra servizi aziendali, compra servizi per la persona.
        /// </summary>
        public static string KeywordsHome {
            get {
                return ResourceManager.GetString("KeywordsHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grandi realtà, miglioramento della persona, gruppo sociale, Jadenka, DavideMilitano, PsicologiADomicilio, AvvocatoClick, Totallympics, CultID Studio.
        /// </summary>
        public static string KeywordsPartners {
            get {
                return ResourceManager.GetString("KeywordsPartners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy, condizioni, persona, {0}, tutela legale, informazioni.
        /// </summary>
        public static string KeywordsPrivacy {
            get {
                return ResourceManager.GetString("KeywordsPrivacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gratis, offerte, oggetti, cerca, beni, servizi, baratto, scambio, {0}.
        /// </summary>
        public static string KeywordsSearch {
            get {
                return ResourceManager.GetString("KeywordsSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compra gratuitamente, categoria, vendita, baratto, acquista, {0}, {1}, {2}, {3} crediti.
        /// </summary>
        public static string KeywordsService {
            get {
                return ResourceManager.GetString("KeywordsService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Siti utili, Utilità sociale, Utilità umana, JustKnock, TaskyJob, GeniUp, WikiLeaks.
        /// </summary>
        public static string KeywordsSiteWeb {
            get {
                return ResourceManager.GetString("KeywordsSiteWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Il primo e-commerce che non vende, ma regala!.
        /// </summary>
        public static string TitleGeneric {
            get {
                return ResourceManager.GetString("TitleGeneric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regala ciò che non usi più o fai volontariato!.
        /// </summary>
        public static string TitleGift {
            get {
                return ResourceManager.GetString("TitleGift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gratis {0} della categoria {1}. Acquista o Baratta..
        /// </summary>
        public static string TitleGood {
            get {
                return ResourceManager.GetString("TitleGood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Una nuovissima e unica moneta virtuale!.
        /// </summary>
        public static string TitleOnlineMoney {
            get {
                return ResourceManager.GetString("TitleOnlineMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerca {0} GRATIS o BARATTO.
        /// </summary>
        public static string TitleSearch {
            get {
                return ResourceManager.GetString("TitleSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ricerche salvate.
        /// </summary>
        public static string TitleSearchSaved {
            get {
                return ResourceManager.GetString("TitleSearchSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tutto gratis! oggetti e servizi gratis con gli {0}!.
        /// </summary>
        public static string TitleSellGratis {
            get {
                return ResourceManager.GetString("TitleSellGratis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gratis {0} della categoria {1}. Acquista o Baratta..
        /// </summary>
        public static string TitleService {
            get {
                return ResourceManager.GetString("TitleService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Siti utili.
        /// </summary>
        public static string TitleSiteWeb {
            get {
                return ResourceManager.GetString("TitleSiteWeb", resourceCulture);
            }
        }
    }
}
